version: '3.8'

services:
  app:
    build:
      context: ../../..
      dockerfile: .docker/file/local/app/Dockerfile
    image: soca:local-latest
    ports:
      - "8000:3000"
    volumes:
      - ../../../src:/app/src
      - ../../../package.json:/app/package.json
      - ../../../package-lock.json:/app/package-lock.json
      - ../../../.env:/app/.env